In [1]:
import pandas as pd
import numpy as np

filepath = 'D:\Project 1\Retail Analysis\Superstore data.csv'
# Load data
df = pd.read_csv(filepath, encoding='latin1')  # eta dataset UTF-8 na hote pare, tai latin1 try koro

# Initial inspection
print(df.shape)
df.head()

(9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [3]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [4]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
# Fix date columns
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df['Postal Code'] = df['Postal Code'].astype(str)

# Verify
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code              object
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [7]:
# Sanity check: Ship Date < Order Date
(df['Ship Date'] < df['Order Date']).sum()

np.int64(0)

In [8]:
# Derived columns
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df['Profit Margin %'] = (df['Profit'] / df['Sales']) * 100

df[['Sales', 'Profit', 'Profit Margin %', 'Shipping Days']].describe()

              Sales       Profit  Profit Margin %  Shipping Days
count   9994.000000  9994.000000      9994.000000    9994.000000
mean     229.858001    28.656896        12.031393       3.958175
std      623.245101   234.260108        46.675435       1.747567
min        0.444000 -6599.978000      -275.000000       0.000000
25%       17.280000     1.728750         7.500000       3.000000
50%       54.490000     8.666500        27.000000       4.000000
75%      209.940000    29.364000        36.250000       5.000000
max    22638.480000  8399.976000        50.000000       7.000000

In [9]:
for col in ['Segment', 'Category', 'Sub-Category', 'Region', 'Ship Mode']:
    print(col, ':', df[col].unique())

Segment : ['Consumer' 'Corporate' 'Home Office']
Category : ['Furniture' 'Office Supplies' 'Technology']
Sub-Category : ['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']
Region : ['South' 'West' 'Central' 'East']
Ship Mode : ['Second Class' 'Standard Class' 'First Class' 'Same Day']

In [10]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\turbo\anaconda3\lib\site-packages (2.9.12)

In [11]:
import io
import psycopg2


# Step 2: Connect
conn = psycopg2.connect(
    host="localhost",
    dbname="Project 01",
    user="postgres",
    password="123456",
    port="5432"
)
cur = conn.cursor()

# Step 3: Table structure create
cur.execute("""
    CREATE TABLE customers (
    customer_id     VARCHAR(20) PRIMARY KEY,
    customer_name   VARCHAR(100),
    segment         VARCHAR(30),
    country         VARCHAR(50)
);

CREATE TABLE products (
    product_id      VARCHAR(30) PRIMARY KEY,
    category        VARCHAR(30),
    sub_category    VARCHAR(30),
    product_name    VARCHAR(200)
);

CREATE TABLE orders (
    row_id             INT PRIMARY KEY,
    order_id           VARCHAR(20) NOT NULL,
    order_date         DATE NOT NULL,
    ship_date          DATE NOT NULL,
    ship_mode          VARCHAR(20),
    customer_id        VARCHAR(20) REFERENCES customers(customer_id),
    product_id         VARCHAR(30) REFERENCES products(product_id),
    city                VARCHAR(50),
    state                VARCHAR(50),
    postal_code         VARCHAR(10),
    region               VARCHAR(20),
    sales               NUMERIC(10,2),
    quantity             INT,
    discount             NUMERIC(4,2),
    profit               NUMERIC(10,2),
    shipping_days        INT,
    profit_margin_pct    NUMERIC(6,2)
);

CREATE INDEX idx_orders_date ON orders(order_date);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_product ON orders(product_id);
""")
conn.commit()

# Step 6a: Extract 3 separate dataframes from my cleaned df

customers_df = df[['Customer ID', 'Customer Name', 'Segment', 'Country']].drop_duplicates(subset='Customer ID')

products_df = df[['Product ID', 'Category', 'Sub-Category', 'Product Name']].drop_duplicates(subset='Product ID')

orders_df = df[['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
                 'Customer ID', 'Product ID', 'City', 'State', 'Postal Code', 'Region',
                 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Days', 'Profit Margin %']]

print(customers_df.shape, products_df.shape, orders_df.shape)

def load_table(df, customers):
    buffer = io.StringIO()
    df.to_csv(buffer, index=False, header=False)
    buffer.seek(0)
    cur.copy_expert(f"COPY {customers} FROM STDIN WITH CSV", buffer)
    conn.commit()
    print(f"{customers} loaded — {len(df)} rows")


def load_table(df, products):
    buffer = io.StringIO()
    df.to_csv(buffer, index=False, header=False)
    buffer.seek(0)
    cur.copy_expert(f"COPY {products} FROM STDIN WITH CSV", buffer)
    conn.commit()
    print(f"{products} loaded — {len(df)} rows")


def load_table(df, orders):
    buffer = io.StringIO()
    df.to_csv(buffer, index=False, header=False)
    buffer.seek(0)
    cur.copy_expert(f"COPY {orders} FROM STDIN WITH CSV", buffer)
    conn.commit()
    print(f"{orders} loaded — {len(df)} rows")

load_table(customers_df, "customers")
load_table(products_df, "products")
load_table(orders_df, "orders")
    
cur.close()
conn.close

(793, 4) (1862, 4) (9994, 17)
customers loaded — 793 rows
products loaded — 1862 rows
orders loaded — 9994 rows

In [12]:
import io
import psycopg2


# Step 2: Connect
conn = psycopg2.connect(
    host="localhost",
    dbname="Project 01",
    user="postgres",
    password="123456",
    port="5432"
)
cur = conn.cursor()

query = """
SELECT 
    o.row_id, o.order_id, o.order_date, o.ship_date, o.ship_mode,
    o.city, o.state, o.postal_code, o.region,
    c.customer_id, c.customer_name, c.segment, c.country,
    p.product_id, p.category, p.sub_category, p.product_name,
    o.sales, o.quantity, o.discount, o.profit, o.shipping_days, o.profit_margin_pct
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON o.product_id = p.product_id;
"""

export_df = pd.read_sql(query, conn)
export_df.to_csv(r'D:\Project 1\Retail Analysis\superstore_export.csv', index=False)
conn.close()

print("Exported:", export_df.shape)

C:\Users\turbo\AppData\Local\Temp\ipykernel_7572\67952408.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  export_df = pd.read_sql(query, conn)

Exported: (9994, 23)